CC = gcc
CFLAGS = -Wall -std=c99 -pedantic

all: main.c
	$(CC) $(CFLAGS) p11.c main.c -o myProgram

# p11.o: p11.c
# 	$(CC) $(CFLAGS) p11.c

# p12.o: p12.c
# 	gcc p12.c -c -std=c99 -g

# p21.o: p21.c
# 	gcc p21.c -c -std=c99 -g

# p22.o: p22.c
# 	gcc p22.c -c -std=c99 -g

